# Generated by Django 6.0.1 on 2026-02-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_parent_address_remove_parent_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='academic_history',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_image',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Unknown Student', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(default='R000', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
