# Generated by Django 6.0.1 on 2026-02-01 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_subject_department_subject_teacher_and_more'),
        ('teachers', '0002_rename_first_name_teacher_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher'),
        ),
    ]
