# Generated by Django 6.0.1 on 2026-02-01 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_mark_delete_marks_delete_subject'),
        ('students', '0003_remove_student_parent_and_more'),
        ('subjects', '0002_remove_subject_department_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ['student__name', 'subject__name']},
        ),
        migrations.AddField(
            model_name='mark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='subjects.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'subject')},
        ),
    ]
