# Generated by Django 6.0.1 on 2026-02-01 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_alter_mark_options_mark_created_at_and_more'),
        ('students', '0003_remove_student_parent_and_more'),
        ('subjects', '0003_alter_subject_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={},
        ),
        migrations.RemoveField(
            model_name='mark',
            name='max_score',
        ),
        migrations.AlterField(
            model_name='mark',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
    ]
