# Generated by Django 6.0.1 on 2026-02-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_unique_together_attendance_subject_and_more'),
        ('students', '0003_remove_student_parent_and_more'),
        ('subjects', '0002_remove_subject_department_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subject', 'date')},
        ),
    ]
